// Regenerates lib/src/stub_flasher.g.dart from esptool's stub flasher JSONs.
//
//   dart run tool/gen_stubs.dart ../esptool/esptool/targets/stub_flasher/2
//
// The JSONs are the Apache/MIT-licensed builds of
// https://github.com/espressif/esp-flasher-stub that ship inside esptool.
// Plugin segments (NAND) are not vendored.
import 'dart:convert';
import 'dart:io';

const _chips = {
  'esp32': 'esp32',
  'esp32s2': 'esp32s2',
  'esp32s3': 'esp32s3',
  'esp32c3': 'esp32c3',
  'esp32c2': 'esp32c2',
  'esp32c6': 'esp32c6',
  'esp32h2': 'esp32h2',
  'esp32p4': 'esp32p4',
};

void main(List<String> args) {
  final dir = Directory(args.single);
  final version = RegExp(r'releases/tag/(v[\d.]+)').firstMatch(File('${dir.path}/README.md').readAsStringSync())!.group(1);
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_stubs.dart from ${dir.path.split('/').skip(dir.path.split('/').length - 4).join('/')} — do not edit.')
    ..writeln('// Stub flasher $version: https://github.com/espressif/esp-flasher-stub (Apache-2.0 / MIT).')
    ..writeln()
    ..writeln("import 'package:esp_defs/esp_defs.dart';")
    ..writeln("import 'stub_flasher.dart';")
    ..writeln()
    ..writeln('const stubFlasherImages = <EspChip, StubFlasherImage>{');
  for (final MapEntry(key: chip, value: file) in _chips.entries) {
    final json = jsonDecode(File('${dir.path}/$file.json').readAsStringSync()) as Map<String, dynamic>;
    String hex(dynamic v) => '0x${(v as int).toRadixString(16)}';
    out
      ..writeln('  EspChip.$chip: StubFlasherImage(')
      ..writeln('    entry: ${hex(json['entry'])},')
      ..writeln('    textStart: ${hex(json['text_start'])},')
      ..writeln("    text: '${json['text']}',")
      ..writeln('    dataStart: ${hex(json['data_start'])},')
      ..writeln("    data: '${json['data']}',")
      ..writeln('    bssStart: ${hex(json['bss_start'])},')
      ..writeln('  ),');
  }
  out.writeln('};');
  File('lib/src/stub_flasher.g.dart').writeAsStringSync(out.toString());
}
