// Regenerates lib/src/efuse_tables.g.dart from espefuse's field definitions.
//
//   dart run tool/gen_efuse_tables.dart ../../../esptool/espefuse
//
// Reads, per chip, `efuse_defs/<chip>.yaml` (the fields, as espefuse shows
// them), `efuse/<chip>/mem_definition.py` (block read addresses and
// protection bits) and `efuse/<chip>/fields.py` (key purposes). Categories
// and value kinds follow espefuse's `set_category_and_class_type`.
import 'dart:io';

import 'package:yaml/yaml.dart';

/// Chip → the YAML variants to generate, each with the lowest chip revision
/// (major * 100 + minor) it applies to.
const _chips = {
  'esp32': {'esp32': 0},
  'esp32s2': {'esp32s2': 0},
  'esp32s3': {'esp32s3': 0},
  'esp32c3': {'esp32c3': 0},
  'esp32c2': {'esp32c2': 0},
  'esp32c6': {'esp32c6': 0},
  'esp32h2': {'esp32h2': 0},
  'esp32p4': {'esp32p4': 0, 'esp32p4_v3.0': 300},
};

void main(List<String> args) {
  final root = args.single;
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_efuse_tables.dart from espefuse — do not edit.')
    ..writeln('// Field definitions: https://github.com/espressif/esptool/tree/master/espefuse (GPL-2.0-or-later).')
    ..writeln()
    ..writeln("import 'chip.dart';")
    ..writeln("import 'efuse.dart';")
    ..writeln()
    ..writeln('const efuseTables = <EspChip, List<EfuseTable>>{');
  for (final MapEntry(key: chip, value: variants) in _chips.entries) {
    final mem = File('$root/efuse/$chip/mem_definition.py').readAsStringSync();
    final fieldsPy = File('$root/efuse/$chip/fields.py').readAsStringSync();
    out.writeln('  EspChip.$chip: [');
    for (final MapEntry(key: file, value: minRevision) in variants.entries) {
      _table(out, chip, mem, fieldsPy, File('$root/efuse_defs/$file.yaml').readAsStringSync(), minRevision);
    }
    out.writeln('  ],');
  }
  out.writeln('};');
  File('lib/src/efuse_tables.g.dart').writeAsStringSync(out.toString());
}

void _table(StringBuffer out, String chip, String mem, String fieldsPy, String yaml, int minRevision) {
  final base = int.parse(RegExp(r'DR_REG_EFUSE_BASE = (0x[0-9A-Fa-f]+)').firstMatch(mem)!.group(1)!);
  out
    ..writeln('    EfuseTable(')
    ..writeln('      baseAddress: ${_hex(base)},')
    ..writeln('      minRevision: $minRevision,')
    ..writeln('      blocks: [');
  final blockLine = RegExp(
      r'\("(\w+)",\s*\[([^\]]*)\],\s*(\d+),\s*__base_(?:rd_)?regs\s*\+\s*(0x[0-9A-Fa-f]+),\s*[^,]+,\s*(None|\d+),\s*(None|\d+|\[[^\]]*\]),\s*(\d+),\s*(None|"\w+")\)');
  final blocks = blockLine.allMatches(mem).toList();
  if (blocks.isEmpty) throw StateError('$chip: no blocks found');
  for (final m in blocks) {
    final aliases = RegExp(r'"(\w+)"').allMatches(m.group(2)!).map((a) => "'${a.group(1)}'").join(', ');
    out
      ..writeln('        EfuseBlock(')
      ..writeln("          name: '${m.group(1)}',")
      ..writeln('          aliases: [$aliases],')
      ..writeln('          index: ${m.group(3)},')
      ..writeln('          readOffset: ${m.group(4)!.toLowerCase()},')
      ..writeln('          words: ${m.group(7)},')
      ..writeln('          writeDisableBit: ${_pyNone(m.group(5)!)},')
      ..writeln('          readDisableBits: ${_bits(m.group(6)!)},')
      ..writeln("          keyPurposeField: ${m.group(8) == 'None' ? 'null' : "'${m.group(8)!.replaceAll('"', '')}'"},")
      ..writeln('        ),');
  }
  out
    ..writeln('      ],')
    ..writeln('      keyPurposes: {');
  final purposes = RegExp(r'KEY_PURPOSES = \[(.*?)\n\s*\]', dotAll: true).firstMatch(fieldsPy)?.group(1) ?? '';
  // Some ids have two names (ECDSA_KEY_P256 and its older ECDSA_KEY).
  final names = <int, List<String>>{};
  for (final p in RegExp(r'\("(\w+)",\s*(\d+),').allMatches(purposes)) {
    names.putIfAbsent(int.parse(p.group(2)!), () => []).add(p.group(1)!);
  }
  for (final MapEntry(:key, :value) in names.entries) {
    out.writeln("        $key: '${value.join(' / ')}',");
  }
  out
    ..writeln('      },')
    ..writeln('      fields: [');
  final efuses = (loadYaml(yaml) as YamlMap)['EFUSES'] as YamlMap;
  for (final MapEntry(key: name as String, value: d as YamlMap) in efuses.entries) {
    if (d['show'] != 'y') continue;
    final type = '${d['type']}';
    final (category, kind) = _classify(name);
    final values = <int, String>{
      for (final v in RegExp(r'''(\d+)\s*:\s*["']([^"']*)["']''').allMatches('${d['dict']}')) int.parse(v.group(1)!): v.group(2)!,
    };
    final alt = '${d['alt']}'.trim();
    // espefuse widens the user data field to the whole block (its CUSTOM_MAC
    // overlaps the tail).
    final bitLength = name == 'BLOCK_USR_DATA' ? 256 : d['len'];
    out
      ..writeln('        EfuseField(')
      ..writeln("          name: '$name',")
      ..writeln('          block: ${d['blk']},')
      ..writeln('          word: ${d['word']},')
      ..writeln('          pos: ${d['pos']},')
      ..writeln('          bitLength: $bitLength,')
      ..writeln('          type: EfuseType.${type == 'bool' ? 'bool' : type.startsWith('bytes') ? 'bytes' : 'uint'},')
      ..writeln('          category: EfuseCategory.$category,')
      ..writeln('          kind: EfuseKind.$kind,')
      ..writeln('          description: ${_str('${d['desc']}')},');
    if (alt.isNotEmpty) out.writeln('          altNames: [${alt.split(' ').map((a) => "'$a'").join(', ')}],');
    if (d['wr_dis'] != null) out.writeln('          writeDisableBit: ${d['wr_dis']},');
    if (d['rd_dis'] != null) out.writeln('          readDisableBits: ${_bits('${d['rd_dis']}')},');
    if (values.isNotEmpty) out.writeln('          values: {${values.entries.map((e) => '${e.key}: ${_str(e.value)}').join(', ')}},');
    out.writeln('        ),');
  }
  out
    ..writeln('      ],')
    ..writeln('    ),');
}

/// espefuse's `set_category_and_class_type`, as (category, kind).
(String, String) _classify(String name) {
  bool has(List<String> words) => words.any(name.contains);
  if (name.startsWith('SPI_PAD_CONFIG')) return ('spiPad', 'plain');
  if (name.contains('USB')) return ('usb', 'plain');
  if (name.contains('WDT')) return ('wdt', 'plain');
  if (name.contains('JTAG')) return ('jtag', 'plain');
  if (has(['FLASH', 'FORCE_SEND_RESUME'])) return ('flash', 'plain');
  if (has(['VDD_SPI_', 'XPD'])) return ('vdd', 'plain');
  if (name.contains('MAC')) return ('mac', ['MAC', 'CUSTOM_MAC', 'MAC_EXT'].contains(name) ? 'mac' : 'plain');
  if (has(['BLOCK_KEY0', 'BLOCK_KEY1', 'BLOCK_KEY2', 'BLOCK_KEY3', 'BLOCK_KEY4', 'BLOCK_KEY5', 'BLOCK1', 'BLOCK2'])) return ('security', 'keyBlock');
  if (has([
    'KEY',
    'SECURE',
    'DOWNLOAD',
    'SPI_BOOT_CRYPT_CNT',
    'KEY_PURPOSE',
    'SECURE_VERSION',
    'DPA',
    'ECDSA',
    'FLASH_CRYPT_CNT',
    'ENCRYPT',
    'DECRYPT',
    'ABS_DONE'
  ])) {
    if (name.startsWith('KEY_PURPOSE')) return ('security', 'keyPurpose');
    if (has(['FLASH_CRYPT_CNT', 'SPI_BOOT_CRYPT_CNT', 'SECURE_VERSION'])) return ('security', 'bitCount');
    return ('security', 'plain');
  }
  if (has(['VERSION', 'WAFER', '_ID', 'PKG', 'PACKAGE', 'REV'])) return ('identity', name == 'OPTIONAL_UNIQUE_ID' ? 'keyBlock' : 'plain');
  if (has(['ADC', 'LDO', 'DBIAS', '_HVT', 'CALIB', 'OCODE', 'TEMPERATURE', 'LSLP', 'DSLP'])) return ('calibration', name == 'TEMP_CALIB' ? 'tSensor' : 'plain');
  return ('config', 'plain');
}

String _hex(int v) => '0x${v.toRadixString(16).padLeft(8, '0')}';
String _pyNone(String v) => v == 'None' ? 'null' : v;

/// A read-disable spec — `None`, `3`, `[0, 1]` or `0 1` — as a Dart list.
String _bits(String v) => '[${RegExp(r'\d+').allMatches(v).map((m) => m.group(0)).join(', ')}]';

String _str(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";
